const projects = [
  {
    "image":"profile-card-component",
    "name":"Profile Card",
    "date":"19/01/2024",
    "level":["newbie", "1"],
    "languages": "html / css",
    "deploy":"pages/profile-card-component/index.html",
    "code":"https://github.com/Vitor-HenriqueAS/Front_End_Mentor/tree/main/pages/profile-card-component",
  },
  {
    "image":"interactive-rating",
    "name":"Interactive Rating",
    "date":"30/08/2022",
    "level":["newbie", "1"],
    "languages": "html / css / js",
    "deploy":"pages/interactive-rating/index.html",
    "code":"https://github.com/Vitor-HenriqueAS/Front_End_Mentor/tree/main/pages/interactive-rating",
  },
  {
    "image":"order-summary",
    "name":"Order Summary",
    "date":"16/08/2022",
    "level":["newbie", "1"],
    "languages": "html / css",
    "deploy":"pages/order-summary/index.html",
    "code":"https://github.com/Vitor-HenriqueAS/Front_End_Mentor/tree/main/pages/order-summary",
  },
  {
    "image":"3-column",
    "name":"3 Column",
    "date":"15/08/2022",
    "level":["newbie", "1"],
    "languages": "html / css",
    "deploy":"pages/3-column-preview/index.html",
    "code":"https://github.com/Vitor-HenriqueAS/Front_End_Mentor/tree/main/pages/3-column-preview",
  },
  {
    "image":"qr-code",
    "name":"QR Code",
    "date":"09/08/2022",
    "level":["newbie", "1"],
    "languages": "html / css",
    "deploy":"pages/qr-code/index.html",
    "code":"https://github.com/Vitor-HenriqueAS/Front_End_Mentor/tree/main/pages/qr-code",
  },
  {
    "image":"nft-equilibrium",
    "name":"NFT Preview Card",
    "date":"07/08/2022",
    "level":["newbie", "1"],
    "languages": "html / css",
    "deploy":"pages/nft-preview-card/index.html",
    "code":"https://github.com/Vitor-HenriqueAS/Front_End_Mentor/tree/main/pages/nft-preview-card",
  },
  {
    "image":"perfume-gabrielle",
    "name":"Product Preview Card",
    "date":"06/08/2022",
    "level":["newbie", "1"],
    "languages": "html / css",
    "deploy":"pages/product-preview-card/index.html",
    "code":"https://github.com/Vitor-HenriqueAS/Front_End_Mentor/tree/main/pages/product-preview-card",
  }
];

export default projects;